### PR TITLE
Adjust margin

### PR DESCRIPTION
**Pull request by nrs32**
Margin on chart must be adjusted to handle having chart dropdowns on left or right of chart.
Chart should adjust width and margin accordingly so that chart and dropdowns do no overlap.
Also see: https://github.com/Eidex/focus-app/pull/1152

### CODE REVIEW

**Comment by dselgo** [comment]
Do you think it would make sense to change `marginLeft` to `margin` and pass the whole margin text? I'm just wondering if there may ever be a need for that.

Also, when we push this it goes straight to prod, but it looks like it shouldn't be an issue. Just wanted to check if this will work in prod and dev.

**Comment by nrs32** [comment]
> Do you think it would make sense to change `marginLeft` to `margin` and pass the whole margin text? I'm just wondering if there may ever be a need for that.

Currently the chart only needs a left margin for when there are left dropdowns. When there are right dropdowns, we only need to change the width of the chart because it automatically aligns left. For top and bottom dropdowns, we just adjust the height of the chart because the divs for the dropdowns move the chart up/down as needed.

So to move the chart around in a given space, we can simply adjust the height or width, unless it must shift to the right, then we need marginLeft as well as width adjusted.

So I don't think we should need margin on any other sides, so it wouldn't be needed. However, margin is less specific which may be better, but I can't think of a reason why we would need to adjust the top, right, or bottom margins.

> Also, when we push this it goes straight to prod, but it looks like it shouldn't be an issue. Just wanted to check if this will work in prod and dev.

I don't think it will be an issue because it only adds styles and does not remove them.

**Comment by dselgo** [comment]
> So to move the chart around in a given space, we can simply adjust the height or width, unless it must shift to the right, then we need marginLeft as well as width adjusted.
If that is that case then why exactly do we need marginLeft at all? If you need to have a left dropdown can't you just adjust the width? How is it different than the right dropdowns? Do the dropdowns use `display: absolute`?

**Comment by nrs32** [comment]
> If that is that case then why exactly do we need marginLeft at all? If you need to have a left dropdown can't you just adjust the width? How is it different than the right dropdowns? Do the dropdowns use `display: absolute`?

Because the dropdowns do use absolute, but then they overlap on top of the chart because the width is updated but the chart stays left. So then there is room on the right even when we want dropdowns on the left. So we must move the chart to the right to make the gap be on the left instead for left dropdowns.

**Pull request merged**
